{{- $c := .Values.rikoo.api -}}
{{- if $c.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rikoo.api.serviceName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "rikoo.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with $c.hpa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rikoo.api.serviceName" . }}
  minReplicas: {{ $c.hpa.minReplicas }}
  maxReplicas: {{ $c.hpa.maxReplicas }}
  metrics:
    {{- with $c.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
    {{- with $c.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
{{- end }}
