{{- $c := .Values.rikoo.worker -}}
{{- if and $c.metrics.serviceMonitor.enabled $c.service.create (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rikoo.worker.serviceName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "rikoo.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
    {{- with $c.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "rikoo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: health
      path: /metrics
      interval: {{ $c.metrics.serviceMonitor.interval }}
{{- end }}
