#!/usr/bin/env bash
# Keeps the two things the settings validation depends on honest.
#
# 1. `rikoo.managedEnvNames` must list every variable the templates set themselves. A template that
#    starts setting a name without that name being listed makes the collision check blind: the
#    operator sets the same key in `settings`, and which one wins depends on render order.
# 2. Every name the templates set must exist in `env-contract.json`, except the few the chart
#    invents for its own plumbing. A name the product stopped reading is a setting that silently
#    does nothing, and a renamed variable is exactly how that happens.
set -uo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
CHART="$HERE/charts/rikoo"
CONTRACT="$CHART/env-contract.json"
HELPERS="$CHART/templates/_helpers.tpl"

# Names the chart invents, no part of the product's contract: the password Kubernetes expands into
# the connection URL, and the two the wait-for-api init container reads.
CHART_OWN='^(RIKOO_DB_PASSWORD|API_READY_URL|WAIT_TIMEOUT_SECONDS)$'

# Known gap, 2026-09-25. The product's code reads these two through an injected environment object,
# which its own scanner cannot see, so its manifest declares only the `_API` spellings. Those exist
# to let one shared environment file serve two containers in a Compose stack. In a cluster each pod
# sets the plain name, which is what this chart does and what the product reads. The contract will
# carry them once the manifest is corrected; until then they are named here, not silently tolerated.
KNOWN_GAP='^(OTEL_METRICS_EXPORTER|OTEL_EXPORTER_PROMETHEUS_PORT)$'

[ -f "$CONTRACT" ] || { echo "✗ $CONTRACT absent: it is generated by the product and shipped with the chart"; exit 2; }

# What the templates actually set, from `- name: X` and from the ConfigMap keys.
set_names="$(
  {
    grep -rhoE '^ *- name: [A-Z][A-Z0-9_]*$' "$CHART/templates/" | sed 's/.*name: //'
    grep -hoE '^  [A-Z][A-Z0-9_]*:' "$CHART/templates/configmap-env.yaml" | tr -d ' :'
  } | sort -u | grep -vE "$CHART_OWN"
)"

# What the helper claims. The define spans several lines, so whitespace is folded.
declared="$(
  awk '/define "rikoo.managedEnvNames"/{f=1;next} f&&/{{- end -}}/{exit} f' "$HELPERS" |
    tr -s ' \n' '\n' | grep -E '^[A-Z][A-Z0-9_]*$' | sort -u
)"

problems=0
missing="$(comm -23 <(echo "$set_names") <(echo "$declared"))"
if [ -n "$missing" ]; then
  problems=1
  echo "✗ set by a template, absent from rikoo.managedEnvNames — the collision check is blind to these:"
  echo "$missing" | sed 's/^/    /'
fi
stale="$(comm -13 <(echo "$set_names") <(echo "$declared"))"
if [ -n "$stale" ]; then
  problems=1
  echo "✗ listed in rikoo.managedEnvNames, set by no template — remove them, or an operator is refused a setting for nothing:"
  echo "$stale" | sed 's/^/    /'
fi

# The contract is a JSON map keyed by name; grep for the quoted key at the right depth.
unknown=""
while IFS= read -r name; do
  grep -qE "^    \"$name\": \{" "$CONTRACT" && continue
  if [[ "$name" =~ $KNOWN_GAP ]]; then gaps="${gaps:-}$name "; continue; fi
  unknown="$unknown$name"$'\n'
done <<< "$set_names"
if [ -n "$unknown" ]; then
  problems=1
  echo "✗ set by a template, unknown to the product's contract — the product may have renamed or dropped them:"
  echo "$unknown" | sed '/^$/d;s/^/    /'
fi

# The operator-facing table is generated from the same contract: stale, it lists names that no longer
# exist, or hides the ones that do.
if ! node "$HERE/tools/variables-doc.mjs" --check >/dev/null 2>&1; then
  problems=1
  echo "✗ charts/rikoo/VARIABLES.md no longer matches the contract — run: make variables-doc"
fi

if [ -n "${gaps:-}" ]; then
  echo "ℹ known gap, tolerated by name: ${gaps}— see the comment at the top of this script."
fi
if [ $problems -eq 0 ]; then
  echo "✓ $(echo "$set_names" | wc -l | tr -d ' ') names set by the templates: all declared, all known to the contract."
  exit 0
fi
exit 1
